/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.frames;

/**
 *
 * @author Bart Jansen
 */
public class NewJPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel1
     */
    public NewJPanel1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        innerPanel = new javax.swing.JPanel();
        lblItemID = new javax.swing.JLabel();
        lblItemID2 = new javax.swing.JLabel();
        lblHoofditem = new javax.swing.JLabel();
        lblItemSoort = new javax.swing.JLabel();
        lblItemCode = new javax.swing.JLabel();
        lblBeschrijving = new javax.swing.JLabel();
        lblLocatie = new javax.swing.JLabel();
        cmbHoofdItem = new javax.swing.JComboBox<>();
        cmbItemSoort = new javax.swing.JComboBox<>();
        cmbItemCode = new javax.swing.JComboBox<>();
        edtBeschrijving = new javax.swing.JTextField();
        edtLocatie = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(600, 128));
        setLayout(new java.awt.GridBagLayout());

        innerPanel.setLayout(new java.awt.GridBagLayout());

        lblItemID.setText("ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        innerPanel.add(lblItemID, gridBagConstraints);

        lblItemID2.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        innerPanel.add(lblItemID2, gridBagConstraints);

        lblHoofditem.setText("Hoofditem:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        innerPanel.add(lblHoofditem, gridBagConstraints);

        lblItemSoort.setText("Itemsoort:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        innerPanel.add(lblItemSoort, gridBagConstraints);

        lblItemCode.setText("Itemcode:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        innerPanel.add(lblItemCode, gridBagConstraints);

        lblBeschrijving.setText("Beschrijving:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        innerPanel.add(lblBeschrijving, gridBagConstraints);

        lblLocatie.setText("Locatie:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        innerPanel.add(lblLocatie, gridBagConstraints);

        cmbHoofdItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbHoofdItem.setPreferredSize(new java.awt.Dimension(150, 20));
        cmbHoofdItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHoofdItemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        innerPanel.add(cmbHoofdItem, gridBagConstraints);

        cmbItemSoort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbItemSoort.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        innerPanel.add(cmbItemSoort, gridBagConstraints);

        cmbItemCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbItemCode.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        innerPanel.add(cmbItemCode, gridBagConstraints);

        edtBeschrijving.setPreferredSize(new java.awt.Dimension(500, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        innerPanel.add(edtBeschrijving, gridBagConstraints);

        edtLocatie.setPreferredSize(new java.awt.Dimension(500, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        innerPanel.add(edtLocatie, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(innerPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbHoofdItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHoofdItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbHoofdItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbHoofdItem;
    private javax.swing.JComboBox<String> cmbItemCode;
    private javax.swing.JComboBox<String> cmbItemSoort;
    private javax.swing.JTextField edtBeschrijving;
    private javax.swing.JTextField edtLocatie;
    private javax.swing.JPanel innerPanel;
    private javax.swing.JLabel lblBeschrijving;
    private javax.swing.JLabel lblHoofditem;
    private javax.swing.JLabel lblItemCode;
    private javax.swing.JLabel lblItemID;
    private javax.swing.JLabel lblItemID2;
    private javax.swing.JLabel lblItemSoort;
    private javax.swing.JLabel lblLocatie;
    // End of variables declaration//GEN-END:variables
}
