/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.frames;
import java.io.File;
import javax.swing.JPanel;
import org.icepdf.ri.common.ComponentKeyBinding;

import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;
/**
 *
 * @author Bart Jansen
 */
public class VoorbeeldWeergaveFrame extends javax.swing.JInternalFrame {

    SwingController controller;
    
    /**
     * Creates new form VoorbeeldWeergaveFrame
     */
    public VoorbeeldWeergaveFrame() {
//        initComponents();
//        String filePath = "d:\\Bart Jansen\\Documents\\Synobsys\\Cursus Outsystems\\OutSystems - Exam 1 - Aantekeningen.pdf";

        // build a controller
        controller = new SwingController();

        // Build a SwingViewFactory configured with the controller
        SwingViewBuilder factory = new SwingViewBuilder(controller);

        // Use the factory to build a JPanel that is pre-configured
        //with a complete, active Viewer UI.
        JPanel viewerComponentPanel = factory.buildViewerPanel();

        // add copy keyboard command
        ComponentKeyBinding.install(controller, viewerComponentPanel);

        // add interactive mouse link annotation support via callback
        controller.getDocumentViewController().setAnnotationCallback(
                new org.icepdf.ri.common.MyAnnotationCallback(
                        controller.getDocumentViewController()));

        getContentPane().add(viewerComponentPanel);
        // Open a PDF document to view
//        controller.openDocument(filePath);
        pack();
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        
    }

    
    public void triggerPreview(String fileName){
//        voorbeeldWeergave1.triggerPreview(fileName);
        controller.openDocument(fileName);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        File f = new File(fileName);
        setTitle("VoorbeeldWeergave: " + f.getName());

    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("VoorbeeldWeergave");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
